# Generated by Django 3.1 on 2020-08-06 20:42

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
       
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(default=None, max_length=150)),
                ('last_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_mobile', models.CharField(blank=True, default=None, error_messages={'unique': 'ya se encuentra un usuario con ese telefono'}, max_length=15, null=True, unique=True)),
                ('phone_home', models.CharField(blank=True, default=None, error_messages={'unique': 'ya se encuentra un usuario con ese telefono'}, max_length=15, null=True, unique=True)),
                ('phone_office', models.CharField(blank=True, default=None, error_messages={'unique': 'ya se encuentra un usuario con ese telefono'}, max_length=15, null=True, unique=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('type_document', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('TA', 'Tarjeta de identidad')], max_length=2)),
                ('document', models.IntegerField()),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
