# Generated by Django 2.2.6 on 2020-10-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_auto_20201026_0031'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulesApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'modules_aplication',
            },
        ),
        migrations.CreateModel(
            name='GroupsModuls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('id_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ModulesApplication')),
            ],
            options={
                'db_table': 'groups_modules',
            },
        ),
    ]
