# Generated by Django 2.2.6 on 2020-10-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groupsmoduls_modulesapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulesapplication',
            name='nickname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
